/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rq_sql;

/**
 *
 * @author patrick
 */
public class RqSQL_Requeteur extends javax.swing.JFrame {

    /**
     * Creates new form RqSQL_Requeteur
     */
    public RqSQL_Requeteur() {
        System.out.println("initialisation requeteur \n");
        initComponents();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Out_Requete = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Sai_Requete = new javax.swing.JTextArea();
        Bt_Executer = new javax.swing.JButton();
        Bt_Parametres = new javax.swing.JButton();
        Bt_About = new javax.swing.JButton();
        Bt_Quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Requeteur SQL");

        Out_Requete.setColumns(20);
        Out_Requete.setRows(5);
        jScrollPane2.setViewportView(Out_Requete);

        Sai_Requete.setColumns(20);
        Sai_Requete.setRows(5);
        Sai_Requete.setText("Saisir ici votre requete");
        jScrollPane3.setViewportView(Sai_Requete);

        Bt_Executer.setText("Executer");
        Bt_Executer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_ExecuterMouseClicked(evt);
            }
        });

        Bt_Parametres.setText("Parametres");
        Bt_Parametres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_ParametresMouseClicked(evt);
            }
        });

        Bt_About.setText("Au sujet");
        Bt_About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_AboutMouseClicked(evt);
            }
        });

        Bt_Quitter.setText("Quitter");
        Bt_Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_QuitterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bt_Executer)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_Parametres)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_About)
                        .addGap(18, 18, 18)
                        .addComponent(Bt_Quitter)
                        .addGap(0, 255, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Executer)
                    .addComponent(Bt_Parametres)
                    .addComponent(Bt_About)
                    .addComponent(Bt_Quitter))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_AboutMouseClicked
        // TODO add your handling code here:
        Rq_Sql.AuSujet();
    }//GEN-LAST:event_Bt_AboutMouseClicked

    private void Bt_QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_QuitterMouseClicked
        // TODO add your handling code here:
        Rq_Sql.Quitter();
    }//GEN-LAST:event_Bt_QuitterMouseClicked

    private void Bt_ParametresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_ParametresMouseClicked
        // TODO add your handling code here:
        Rq_Sql.Parametres();
    }//GEN-LAST:event_Bt_ParametresMouseClicked

    private void Bt_ExecuterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_ExecuterMouseClicked
        // TODO add your handling code here:
        Rq_Sql.Executer();
    }//GEN-LAST:event_Bt_ExecuterMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_About;
    private javax.swing.JButton Bt_Executer;
    private javax.swing.JButton Bt_Parametres;
    private javax.swing.JButton Bt_Quitter;
    private javax.swing.JTextArea Out_Requete;
    private javax.swing.JTextArea Sai_Requete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
