/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rq_sql;

/**
 *
 * @author patrick
 */
public class RqSQL_About extends javax.swing.JFrame {

    String Text_About = "<html><head>\n" +
            "<link href=\"http://www.st2msi.net/parm/style.css\" type=\"text/css\" rel=\"stylesheet\">\n"+
            "</head>\n<body bgcolor=\"white\">\n<table width=\"380\"><tr><td align=\"center\">\n" +
            "<IMG SRC=\"http://www.st2msi.net/img/Dendro_2.gif\" alt=\"Iratus Ranam\" title=\"Dendrobate\">" +
            "</td></tr><tr><td align=\"center\">\nRequeteur RqSQL ecrit en Java" +
            "<h2>BTS SIO SLAM</h2>\n" +
            "<a href=\"http://www.st2msi.net/agora\">Lycée Claude Nouga - 82300 MONTEILS</a>"+
                "</td></tr></div></body></html>\n";
    
    /**
     * Creates new form RqSQL_About
     */
    public RqSQL_About() {
        initComponents();
        HTML_Panel.setText(Text_About);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HTML_Panel = new javax.swing.JLabel();

        HTML_Panel.setText("HTML");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HTML_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HTML_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HTML_Panel;
    // End of variables declaration//GEN-END:variables
}
